// Code generated by mockery v2.37.1. DO NOT EDIT.

package notifier

import (
	"context"
	mock "github.com/stretchr/testify/mock"
	mail "gopkg.in/mail.v2"
)

// Dialer is an autogenerated mock type for the Dialer type
type DialerMock struct {
	mock.Mock
}

// DialAndSend provides a mock function with given fields: m
func (_m *DialerMock) DialAndSend(m ...*mail.Message) error {
	_va := make([]interface{}, len(m))
	for _i := range m {
		_va[_i] = m[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(...*mail.Message) error); ok {
		r0 = rf(m...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDialer creates a new instance of Dialer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDialerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *DialerMock {
	mock := &DialerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Client is an autogenerated mock type for the Client type
type ClientMock struct {
	mock.Mock
}

// NotifyTo provides a mock function with given fields: _a0, _a1
func (_m *ClientMock) NotifyTo(_a0 context.Context, _a1 NotifyToOptions) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, NotifyToOptions) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClientMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ClientMock {
	mock := &ClientMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

